addition = (lambda x, y: x + y ) (1,2)
subtraction = (lambda x, y: x - y) (5,2)
multiplication = (lambda x, y: x * y) (6,8)
division = (lambda x, y: x / y)(8,2) 
print (addition)
print (subtraction)
print (multiplication)
print (division)
